### ISSUE TITLE
Add npmPublish to FuseBox

### ISSUE THREAD

**Issue by clitetailor** [react-epic/react-epic#17]
- Add `npm run deploy` command to `package.json`
- Add `deploy` task to FuseBox that run `npm test`, check whether tests passed, check prettier before running `npmPublish`

Additional:
- Check arguments from cli command. For example `node fuse deploy minor` will bump minor version, `node fuse deploy major` will bump major version. If no argument is provided, the `prerelease` version will be choosed.

Other Descriptions:
- We use `npm run deploy` instead of `npm publish` to avoid making mistake.
- PRs are welcome regardless PR quality and completeness.

**Comment by 9reeno** [comment]
I'll pick this up, shouldn't take me too long!

**Comment by 9reeno** [comment]
Hey @clitetailor, finished this one up today. See the PR I created above. 

Let me know what you think! Thanks.

**Comment by clitetailor** [comment]
I this is okey already, i think. I got enough hints now. I will have merge this PR and have further tweaks later. I just wonder whether FuseBox have API for such these things. Something like:

```jsx
await src('./src').run('npm test').exec()
```

I asked on Gitter but no one replied, maybe i should contribute it a little bit when i have time. 🤔

However, Thanks for you contribution! This is the first time i work with one contributor. Glad to see that you helped and happy Hacktoberfest! 😄

**Comment by 9reeno** [comment]
Thanks! I am happy to help. Never had my hands on FuseBox before, it looks like a tool with more than meets the eye... I scanned through the docs for a more intuitive way to run tasks (and get arguments like major and minor), but I came up with nothing.

**Comment by clitetailor** [comment]
Yeah, it's still new tech and little be known. The docs and everything is still bleeding edge IMO but i think it's worth to expect more. I'm not a kind of people that love to do everything my ownself too! 😀
